import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavOpt from "@/components/nav_option";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
let loggedin = false;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(process.env.BACKEND_URL);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <nav className="bg-white border-gray-300 dark:bg-gray-500">
          <div className="flex flex-wrap items-center justify-between p-0 mx-auto">
            <a href="/">
              <img
                src="/logo.png"
                width="50"
                height="50"
                className="m-0 p-0 ml-2"
              ></img>
            </a>
            <ul className="font-medium flex p-1 mt-0 border border-gray-100 rounded-lg bg-gray-50 rtl:space-x-reverse bg-gray-800 border-gray-700 mt-2 m-2">
              <NavOpt href="/" text="home"></NavOpt>
              <NavOpt href="/dashboard" text="dashboard"></NavOpt>
              <NavOpt
                href={loggedin ? "/user" : "/user/register"}
                text="user"
              ></NavOpt>
              <NavOpt href="/market" text="market"></NavOpt>
              <NavOpt href="/market/cart" text="cart"></NavOpt>
            </ul>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
