import type { Metadata } from "next";
import "./globals.css";
import NavOpt from "@/components/NavOption";
import { cookies } from "next/headers";
import { getDictionary } from "./dictionaries";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}) {
  const cookie = cookies();
  const dict = await getDictionary(params.lang);

  const loggedin: boolean = (await cookie.get("token")) != undefined;
  console.log(loggedin);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <nav className="bg-white border-gray-300 dark:bg-gray-500">
          <div className="flex flex-wrap items-center justify-between p-0 mx-auto">
            <a href="/">
              <img
                src="/logo.png"
                width="50"
                height="50"
                className="m-0 p-0 ml-2"
              ></img>
            </a>
            <ul className="font-medium flex p-1 mt-0 border border-gray-100 rounded-lg bg-gray-50 rtl:space-x-reverse bg-gray-800 border-gray-700 mt-2 m-2">
              {/* <NavOpt
                href={loggedin ? "/user" : "/user/login"}
                text="User"
              ></NavOpt> */}
              <NavOpt href="/rail" text={dict.nav.rail}></NavOpt>
              <NavOpt href="/metro" text={dict.nav.metro}></NavOpt>
              <NavOpt href="/bus" text={dict.nav.bus}></NavOpt>
            </ul>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
